# Generated by Django 5.1.4 on 2025-01-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='uploads/')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='outputs/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
